name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - uses: burrunan/gradle-cache-action@v1
      name: Cache gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Detekt Code Style
      continue-on-error: true
      run: ./gradlew clean detekt

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        reviewdog -reporter=github-pr-check -f=checkstyle -name="detekt" <${{ github.workspace }}/app/build/reports/detekt/detekt.sarif


    - name: Build with Gradle
      run: ./gradlew assembleRelease
