name: FloatingX CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    name: install Java and Gradle
    runs-on: ubuntu-latest
    container:
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - uses: burrunan/gradle-cache-action@v1
      name: Cache gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

  code-style:
    name: Code Scanning
    container: ${{ needs.init.container }}
    runs-on: ${{ needs.init.runner.os }}
    continue-on-error: true
    needs: [init]
    steps:
    - name: Run Detekt
      run: ./gradlew clean detekt
    - name: Upload SARIF to Github using the upload-sarif action
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: ${{ github.workspace }}/app/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}

  build:
    name: FloatingX Build
    runs-on: ubuntu-latest
    needs: [init, code-style]
    steps:
    - name: Build with Gradle
      run: ./gradlew assembleRelease
